Repository AllexisAlvarico/JAMHS_Flutter, pull requests merged in 2021-04, with the labels that each got.

#24 Oral Histories now open a Youtube Link when clicked.
  assets/images/thumb1.png
  assets/images/thumb2.png
  assets/images/thumb3.png
  lib/collection.dart
  pubspec.yaml
Labels: enhancement

#25 Cards home
  lib/ArtifactArticlesCards.dart
  lib/ArtifactCollectionCards.dart
  lib/aboutus.dart
  lib/articlepage.dart
  lib/artifactView.dart
  lib/collection.dart
  lib/displayView.dart
  lib/floorPlanView.dart
  lib/fullscreenVid.dart
  lib/homepage.dart
  lib/splash.dart
Labels: enhancement

#27 About Us Scaling Fix & Hyperlink
  lib/aboutus.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, screens

#26 Ios clean up
  lib/homepage.dart
  lib/main.dart
  lib/size_config.dart
Labels: improvement

#30 Update icons
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon100.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon114.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon128.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon144.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon152.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon16.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon167.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon20.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon256.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon32.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon50.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon512.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon57.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon64.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon72.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon76.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Iconwatch.png
  lib/collection.dart
Labels: improvement
