Repository AllexisAlvarico/JAMHS_Flutter, pull requests merged in 2021-03, with the labels that each got.

#1 Splash screen
  .vscode/launch.json
  assets/logo/jamhs.jpg
  lib/homepage.dart
  lib/main.dart
  lib/splash.dart
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement, merging, screens

#2 Homepage
  assets/images/homelogo.png
  lib/aboutus.dart
  lib/article.dart
  lib/collection.dart
  lib/homepage.dart
  lib/splash.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement, merging, screens

#3 Collections
  assets/images/hewbrew_artifact.jpg
  assets/images/m1911.png
  assets/images/moh_book.jpg
  assets/images/tibur_hat.jpg
  assets/images/tibur_pin.jpg
  assets/images/tibur_uniform.jpg
  lib/ArtifactCard.dart
  lib/collection.dart
Labels: enhancement, merging, screens

#5 About Us Page Implementation
  assets/images/calguard.png
  assets/images/exbibit.png
  assets/images/facebook.png
  assets/images/instagram.png
  assets/images/paypal.png
  assets/images/siteline.png
  assets/images/twitter.png
  assets/images/vshp.png
  lib/aboutus.dart
Labels: enhancement, merging, screens

#6 changed the donate to virtual tours
  lib/homepage.dart
  lib/virtualTourpage.dart
Labels: enhancement, merging, screens

#7 Triples on About Page now scale appropriately.
  lib/aboutus.dart
Labels: bugfix, screens

#8 Articlepage
  assets/images/isadore.jpg
  assets/images/jack.jpg
  assets/images/john.png
  assets/images/raymond.png
  lib/ArtifactCard.dart
  lib/aboutus.dart
  lib/article.dart
  lib/articlepage.dart
  lib/collection.dart
  lib/homepage.dart
  lib/viewpage.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, merging, screens

#10 Start of Virtual Tours with Panoramic Image
  assets/images/DisplayPanoramicOne.jpg
  assets/images/Test.jpg
  lib/VirtualTour.dart
  lib/virtualTourpage.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, merging, screens

#11 Screen resolutions
  lib/ArtifactCard.dart
  lib/aboutus.dart
  lib/articlepage.dart
  lib/artifactView.dart
  lib/collection.dart
  lib/homepage.dart
  lib/modelView.dart
  lib/size_config.dart
  lib/splash.dart
  lib/viewpage.dart
Labels: enhancement, merging

#12 Populated the articlepage with content
  assets/images/David_Salisbury_Franks.jpg
  assets/images/Defenders at Fort McHenry.jpg
  assets/images/Defenders at the Alamo.jpg
  assets/images/Julius_Stahel.jpg
  assets/images/abraham_charles_myers.jpg
  assets/images/abraham_cohn.jpg
  assets/images/ben-l-salomon.jpg
  assets/images/benjamin-kaufman.jpg
  assets/images/benjamin_levy.jpg
  assets/images/david_urbansky.jpg
  assets/images/eddit_jacobson.jpg
  assets/images/frances_slanger.jpg
  assets/images/francis_salvador.jpg
  assets/images/harry_s_truman.jpg
  assets/images/isadore-s-jachman.jpg
  assets/images/isadore.jpg
  assets/images/jacbonson_and_truman.jpg
  assets/images/jack.jpg
  assets/images/jack_h_jacobs.jpg
  assets/images/jewish_units_in_civil_war.jpg
  assets/images/john.png
  assets/images/john_levitow.jpg
  assets/images/leonard-m-kravitz.jpg
  assets/images/leopold-karpeles.jpg
  assets/images/life_and_leadership_from_jewish_command_sergeant_major.jpg
  assets/images/maurice_juth.jpg
  assets/images/mickey_marcus.jpg
  assets/images/mordecai_myers.jpg
  assets/images/mordecai_sheftall.jpg
  assets/images/moritz-morris.jpg
  assets/images/moses_jacob_ezekiel.jpg
  assets/images/raymond-zussman.jpg
  assets/images/raymond.png
  assets/images/richard_stern.jpg
  assets/images/salomon_brothers.jpg
  assets/images/sam_sachs.jpg
  assets/images/simon_shuler.jpg
  assets/images/stuart_wolfer.jpg
  assets/images/sydney-g-gumpertz.jpg
  assets/images/the_california_column.jpg
  assets/images/tibor_rubin.jpg
  assets/images/truman_holding_torah_given_by_weizmann.jpg
  assets/images/truman_statement_recognizing_israel.jpg
  assets/images/uriah-p-levy.jpg
  assets/images/william-sawelson.jpg
  assets/images/william-shermin.jpg
  lib/articlepage.dart
Labels: enhancement, merging

#14 Screen rotation
  lib/ArtifactArticlesCards.dart
  lib/ArtifactCard.dart
  lib/ArtifactCollectionCards.dart
  lib/aboutus.dart
  lib/articlepage.dart
  lib/artifactView.dart
  lib/collection.dart
  lib/homepage.dart
  lib/pdfView.dart
  lib/splash.dart
Labels: enhancement, merging, screens

#15 Fixed single column problem in articles screen for phone sizes - Test…
  lib/ArtifactArticlesCards.dart
  lib/articlepage.dart
  lib/homepage.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, merging, screens

#18 JAMHS Link for About Us
  lib/aboutus.dart
Labels: bugfix, improvement, screens

#17 Fullscreen video
  lib/collection.dart
  lib/fullscreenVid.dart
  lib/size_config.dart
  lib/videoView.dart
Labels: enhancement, screens

#20 Screen2.0
  lib/ArtifactArticlesCards.dart
  lib/ArtifactCollectionCards.dart
  lib/aboutus.dart
  lib/articlepage.dart
  lib/artifactView.dart
  lib/collection.dart
  lib/homepage.dart
  lib/pdfView.dart
  lib/size_config.dart
  lib/viewpage.dart
Labels: enhancement, improvement

#22 Back Button for Fullscreen Video
  lib/fullscreenVid.dart
  lib/videoView.dart
Labels: enhancement, screens
